using UnityEngine;

namespace CityGenerator.Runtime
{
    /// <summary>
    /// Read/query entry point for a generated city's data at runtime (Editor Play Mode and player
    /// builds alike). Resolves the active <see cref="CityGeneratorInfo"/> once (lazily, cached) and
    /// every module reads straight from it; every getter returns a safe default
    /// (0/false/<see cref="Vector2Int.zero"/>/<see cref="Vector3.zero"/>/null) when
    /// <see cref="IsCityAvailable"/> is false, never throws.
    /// <para>
    /// The cache is never invalidated: this API assumes a single generated city per Play session,
    /// the same assumption the rest of the tool makes today. Regenerating the city at runtime
    /// (outside this spec's scope) would leave the cached reference pointing at a destroyed object.
    /// </para>
    /// </summary>
    public static class CityGeneratorAPI
    {
        private static CityGeneratorInfo cachedInfo;

        private static CityGeneratorInfo Info
        {
            get
            {
                if (cachedInfo == null)
                    cachedInfo = Object.FindFirstObjectByType<CityGeneratorInfo>();
                return cachedInfo;
            }
        }

        /// <summary>True once a <see cref="CityGeneratorInfo"/> has been resolved — i.e. a city generated by the tool exists in the loaded scene(s).</summary>
        public static bool IsCityAvailable => Info != null;

        public static class City
        {
            public static bool IsCustomGrid() => Info != null && Info.useCustomGrid;
            public static Vector2Int GetGridSize() => Info != null ? Info.gridSize : Vector2Int.zero;
            public static int GetBlockCount() => Info != null ? Info.blockCount : 0;
            public static int GetBuildingCount() => Info != null ? Info.buildingCount : 0;
            public static int GetPlazaCount() => Info != null ? Info.plazaCount : 0;
            public static int GetCustomPlaceCount() => Info != null ? Info.customPlaceCount : 0;
            public static int GetLampCount() => Info != null ? Info.lampCount : 0;
            public static int GetBinCount() => Info != null ? Info.binCount : 0;
            public static int GetStreetTreeCount() => Info != null ? Info.streetTreeCount : 0;
            public static int GetTrafficLightCount() => Info != null ? Info.trafficLightCount : 0;
            public static bool IsSeeded() => Info != null && Info.useCustomSeed;
            public static int GetSeed() => Info != null ? Info.seed : 0;

            public static bool IsDayNightEnabled() => Info != null && Info.dayNightCycle != null && Info.dayNightCycle.enabled;

            public static void SetDayNightEnabled(bool enabled)
            {
                if (Info != null && Info.dayNightCycle != null)
                    Info.dayNightCycle.enabled = enabled;
            }

            public static float GetCurrentHour() => Info != null && Info.dayNightCycle != null ? Info.dayNightCycle.currentHour : 0f;

            public static void SetHour(float hour)
            {
                if (Info != null && Info.dayNightCycle != null)
                    Info.dayNightCycle.ApplySun(hour);
            }
        }

        public static class Player
        {
            public static bool IsEnabled() => Info != null && Info.playerEnabled && Info.player != null;
            public static Vector3 GetPosition() => Info != null && Info.player != null ? Info.player.position : Vector3.zero;
            public static bool IsFreeViewActive() => Info != null && Info.freeCameraController != null && Info.freeCameraController.IsActive;
        }

        public static class Traffic
        {
            public static bool IsEnabled() => Info != null && Info.trafficEnabled;
            public static int GetVehicleCount() => Info != null && Info.trafficManager != null ? Info.trafficManager.AgentCount : 0;
        }

        public static class Pedestrians
        {
            public static bool IsEnabled() => Info != null && Info.pedestriansEnabled;
            public static int GetPedestrianCount() => Info != null && Info.pedestrianManager != null ? Info.pedestrianManager.AgentCount : 0;
            public static int GetCustomPedestrianCount() => Info != null ? Info.customPedestrianCount : 0;
        }

        public static class Minimap
        {
            public static bool IsEnabled() => Info != null && Info.minimapHUD != null;
            public static int GetPointOfInterestCount() => Info != null && Info.minimapData != null ? Info.minimapData.pointsOfInterest.Count : 0;
            public static float GetViewRadiusMeters() => Info != null && Info.minimapHUD != null ? Info.minimapHUD.ViewRadiusMeters : 0f;

            public static void SetViewRadiusMeters(float meters)
            {
                if (Info != null && Info.minimapHUD != null)
                    Info.minimapHUD.ViewRadiusMeters = meters;
            }

            public static bool IsVisible() => Info != null && Info.minimapHUD != null && Info.minimapHUD.gameObject.activeSelf;

            public static void SetVisible(bool visible)
            {
                if (Info != null && Info.minimapHUD != null)
                    Info.minimapHUD.gameObject.SetActive(visible);
            }
        }

        public static class Audio
        {
            public static bool IsAmbienceEnabled() => Info != null && Info.ambienceEnabled;
            public static int GetAmbienceClipCount() => Info != null ? Info.ambienceClipCount : 0;
            public static bool IsPlazaAudioEnabled() => Info != null && Info.plazaAudioEnabled;
            public static int GetPlazaAudioSourceCount() => Info != null ? Info.plazaAudioSourceCount : 0;
        }
    }
}
